// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@paygo.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/audit/accounts/{accountId}": {
            "get": {
                "description": "Audit an account to detect fraud by comparing ledger entries with transaction history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "Audit a specific account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Audit result",
                        "schema": {
                            "$ref": "#/definitions/paygo_internal_domain_service.AuditResult"
                        }
                    },
                    "400": {
                        "description": "Invalid account ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Returns pong to verify the server is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/transfers": {
            "post": {
                "description": "Transfer money from one account to another",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transfers"
                ],
                "summary": "Transfer money between accounts",
                "parameters": [
                    {
                        "description": "Transfer details",
                        "name": "transfer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/paygo_internal_api_dto.TransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transfer successful",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "paygo_internal_api_dto.TransferRequest": {
            "type": "object",
            "required": [
                "amount",
                "from_account_id",
                "to_account_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "from_account_id": {
                    "type": "string"
                },
                "to_account_id": {
                    "type": "string"
                }
            }
        },
        "paygo_internal_domain_service.AuditResult": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "account_number": {
                    "type": "string"
                },
                "actual_balance": {
                    "type": "number"
                },
                "audited_at": {
                    "type": "string"
                },
                "balance_discrepancy": {
                    "type": "number"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "expected_balance": {
                    "type": "number"
                },
                "fraud_types": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/paygo_internal_domain_service.FraudType"
                    }
                },
                "ledger_entries_count": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/paygo_internal_domain_service.AuditStatus"
                },
                "transaction_count": {
                    "type": "integer"
                }
            }
        },
        "paygo_internal_domain_service.AuditStatus": {
            "type": "string",
            "enum": [
                "VALID",
                "FRAUDULENT",
                "INCOMPLETE"
            ],
            "x-enum-varnames": [
                "AuditStatusValid",
                "AuditStatusFraudulent",
                "AuditStatusIncomplete"
            ]
        },
        "paygo_internal_domain_service.FraudType": {
            "type": "string",
            "enum": [
                "BALANCE_MISMATCH",
                "MISSING_LEDGER_ENTRY",
                "ORPHANED_LEDGER_ENTRY"
            ],
            "x-enum-varnames": [
                "FraudTypeBalanceMismatch",
                "FraudTypeMissingLedgerEntry",
                "FraudTypeOrphanedLedgerEntry"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "PayGo API",
	Description:      "Payment and money transfer API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
